#!/usr/bin/sudo bash
#2/1/23
#Steven Barnabei
#Purpose is to be able to compile existing network addresses on a network you are connected to and scan ports for security flaws such as opened ports
on machines that should have no open ports, so you're able to fix those flaws.

ip address show scope global | grep "brd" | grep 'inet' | cut -d " " -f 6 | cut -d '/' -f 1 | cut -d "." -f 1,2,3 | uniq > octets.txt

#set variable to the output of octets.txt

OCTETS=$(cat octets.txt)

#create new .txt for the class C network address named after the class C network

echo "" > $OCTETS.txt

#loop ping for all addresses in network

for ip in {1..254}
do
  ping -c 1 $OCTETS.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" >> $OCTETS.txt &
done

cat $OCTETS.txt

#scan
nmap -sS -iL $OCTETS.txt

exit
