#!/usr/bin/sudo bash
#2/1/23
#Steven Barnabei
#Purpose is to be able to compile existing network addresses on a network you are connected to and scan ports for security flaws such as opened ports
on machines that should have no open ports, so you're able to fix those flaws.

#Get class C Network address

ip address show scope global | grep "brd" | grep 'inet' | cut -d " " -f 6 | cut -d '/' -f 1 | cut -d "." -f 1-3 | uniq > address.txt

#set variable to the output of address.txt

ADRESSES=$(cat address.txt)

#create new .txt for the class C network address named after the class C network

echo "" > $ADRESSES.txt

#loop ping for all addresses in network

for ip in {1..254}
do
  ping -c 1 $ADRESSES.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" >> $ADRESSES.txt &
done

cat $ADRESSES.txt

#scan
nmap -sS -iL $ADRESSES.txt

exit


#Thank you to Hackpens2246 https://www.youtube.com/@hackpens2246 for his tutorial on bash scripting with nmap that influenced this code.
